
# Mapeo de tipos relevantes para seguridad peatonal y sus pesos 
CRIME_WEIGHTS_MAP = {
    "ROBO": 1.0,
    "HOMICIDIO": 1.0,
    "VIOLACION DE LA LIBERTAD SEXUAL": 1.0,
    "VIOLACION DE LA LIBERTAD PERSONAL": 0.9,
    "EXTORSION": 0.9,
    "TRATA DE PERSONAS": 0.9,
    "LESIONES": 0.8,
    "HURTO": 0.7,
    "PAZ PUBLICA": 0.6,
    "PELIGRO COMUN": 0.6,
    "DAÑOS": 0.5,
    "RECEPTACION": 0.4,
    "VIOLACION DE DOMICILIO": 0.4,
    "EXPOSICION A PELIGRO O ABANDONO DE PERSONAS EN PELIGRO": 0.8
}

# Distritos
TARGET_DISTRICTS = [
    # --- LIMA ---
    "Ancón, Lima, Peru",
    "Ate, Lima, Peru",
    "Barranco, Lima, Peru",
    "Breña, Lima, Peru",
    "Carabayllo, Lima, Peru",
    "Chaclacayo, Lima, Peru",
    "Chorrillos, Lima, Peru",
    "Cieneguilla, Lima, Peru",
    "Comas, Lima, Peru",
    "El Agustino, Lima, Peru",
    "Independencia, Lima, Peru",
    "Jesús María, Lima, Peru",
    "La Molina, Lima, Peru",
    "La Victoria, Lima, Peru",
    "Lima District, Lima, Peru",
    "Lince, Lima, Peru",
    "Los Olivos, Lima, Peru",
    "Lurigancho, Lima, Peru",
    "Lurín, Lima, Peru",
    "Magdalena del Mar, Lima, Peru",
    "Miraflores, Lima, Peru",
    "Pachacámac, Lima, Peru",
    "Pucusana, Lima, Peru",
    "Pueblo Libre, Lima, Peru",
    "Puente Piedra, Lima, Peru",
    "Punta Hermosa, Lima, Peru",
    "Punta Negra, Lima, Peru",
    "Rímac, Lima, Peru",
    "San Bartolo, Lima, Peru",
    "San Borja, Lima, Peru",
    "San Isidro, Lima, Peru",
    "San Juan de Lurigancho, Lima, Peru",
    "San Juan de Miraflores, Lima, Peru",
    "San Luis, Lima, Peru",
    "San Martín de Porres, Lima, Peru",
    "San Miguel, Lima, Peru",
    "Santa Anita, Lima, Peru",
    "Santa María del Mar, Lima, Peru",
    "Santa Rosa, Lima, Peru",
    "Santiago de Surco, Lima, Peru",
    "Surquillo, Lima, Peru", 
    "Villa El Salvador, Lima, Peru",
    "Villa María del Triunfo, Lima, Peru",
    
    # --- CALLAO ---
    "Bellavista, Callao, Peru",
    "Callao District, Callao, Peru", 
    "Carmen de la Legua Reynoso, Callao, Peru",
    "La Perla, Callao, Peru", 
    "La Punta, Callao, Peru",
    "Mi Perú, Callao, Peru",
    "Ventanilla, Callao, Peru"
]